#!/usr/bin/env bash
set -euo pipefail

# KSB: Key station builder

export KSB_PROJECT_ROOT="$(dirname "$(realpath "$0")")"

function ksb() {
  target="${1}"

  case "${target}" in
    toolchains)
      "${KSB_PROJECT_ROOT}/ksb-toolchains.sh" "${@:2}"
    ;;
    firmware)
      ksb toolchains
      . "${KSB_PROJECT_ROOT}/.toolchains/use-avr.sh"
      pushd "${KSB_PROJECT_ROOT}/keystation-firmware/"
      cargo "${@:2}"
      popd
    ;;
  esac
}

ksb "${@:1}"