KEY_CONTROLLER_VERSION = 0.0.1
KEY_CONTROLLER_SITE = $(BR2_EXTERNAL_KBS_PATH)/../system-components
KEY_CONTROLLER_SITE_METHOD = local
KEY_CONTROLLER_SUBDIR = key-controller
KEY_CONTROLLER_INSTALL_TARGET = YES
KEY_CONTROLLER_DEPENDENCIES = host-rustc key-firmware
KEY_CONTROLLER_SERVICE_FILE = S10key-controller

define KEY_CONTROLLER_INSTALL_SERVICE
	$(INSTALL) -D -m 755 $(KEY_CONTROLLER_PKGDIR)/$(KEY_CONTROLLER_SERVICE_FILE) $(TARGET_DIR)/etc/init.d/$(KEY_CONTROLLER_SERVICE_FILE)
endef

KEY_CONTROLLER_POST_INSTALL_TARGET_HOOKS += KEY_CONTROLLER_INSTALL_SERVICE

KEY_CONTROLLER_POST_RSYNC_HOOKS += POST_RSYNC_CARGO_VENDOR

$(eval $(cargo-package))