#!/bin/sh

key_controller_bin="key-controller"
key_controller_path="/usr/bin/${key_controller_bin}"
key_controller_log="/var/log/${key_controller_bin}.log"

[ -f "${key_controller_path}" ] || exit 0

umask 077

log() {
	echo "$1" | tee /dev/kmsg >> "${key_controller_log}"
}

start() {
    "${key_controller_path}" >> "${key_controller_log}" 2>&1 &
}
stop() {
    killall -q "${key_controller_bin}"
}
restart() {
    stop
    start
}

case "$1" in
  start)
    log "starting ${key_controller_bin}"
    start
    ;;
  stop)
    log "stopping ${key_controller_bin}"
    stop
    ;;
  restart|reload)
    log "restarting ${key_controller_bin}"
    restart
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $?
