KEYBOARD_FIRMWARE_VERSION = 0.0.1
KEYBOARD_FIRMWARE_SITE = $(BR2_EXTERNAL_KBS_PATH)/../firmware
KEYBOARD_FIRMWARE_SITE_METHOD = local
KEYBOARD_FIRMWARE_SUBDIR = keyboard
KEYBOARD_FIRMWARE_INSTALL_TARGET = YES

KEYBOARD_FIRMWARE_PROFILE = release
KEYBOARD_FIRMWARE_ARTIFACT_PATH = ${KSB_BUILD_DIR}/cargo-target/avr-atmega328p/$(KEYBOARD_FIRMWARE_PROFILE)/
KEYBOARD_FIRMWARE_BIN = keyboard.elf

define KEYBOARD_FIRMWARE_BUILD_CMDS
	KSB_NO_LOCK="buildroot" ${KSB} firmware keyboard build --profile $(KEYBOARD_FIRMWARE_PROFILE);
endef

define KEYBOARD_FIRMWARE_INSTALL_TARGET_CMDS
	mkdir -p $(TARGET_DIR)/usr/share/;
	$(INSTALL) -D -m 655 $(KEYBOARD_FIRMWARE_ARTIFACT_PATH)/$(KEYBOARD_FIRMWARE_BIN) $(TARGET_DIR)/usr/share/$(KEYBOARD_FIRMWARE_BIN)
	$(INSTALL) -D -m 655 $(KEYBOARD_FIRMWARE_ARTIFACT_PATH)/keyboard-version.txt $(TARGET_DIR)/usr/share/keyboard-version.txt
endef

$(eval $(generic-package))