#!/usr/bin/env bash
#-Help: Run tool from tools directory
#-Use: <tool name>

set -euo pipefail
source "${KSB_SCRIPTS_LIB_DIR}/logging.sh"

tool_name="${1}"
tool_dir="${KSB_PROJECT_ROOT}/tools/${tool_name}"

if [ ! -d "${tool_dir}" ]; then
  log_fatal "Can't find tool ${tool_name}"
fi

pushd "${tool_dir}"
ksb-cargo run "${@:2}"
popd