#!/usr/bin/env bash
#-Help: Wraps buildroot to include custom packages

set -euo pipefail
source "${KSB_SCRIPTS_LIB_DIR}/logging.sh"

# TODO: Condense into one file

export KSB_BUILDROOT_DIR="${KSB_VENDOR_DIR}/buildroot"
export KSB_BUILDROOT_EXTERNAL_TREE="${KSB_PROJECT_ROOT}/buildroot"
export KSB_BUILDROOT_GIT_CONFIG="${KSB_BUILDROOT_EXTERNAL_TREE}/configs/keystation_defconfig"
export KSB_BUILDROOT_OUTPUT_DIR="${KSB_BUILD_DIR}/buildroot"
export KSB_BUILDROOT_CONFIG="${KSB_BUILDROOT_OUTPUT_DIR}/.config"
export KSB_BUILDROOT_BUILD_DIR="${KSB_BUILDROOT_OUTPUT_DIR}/build"
export KSB_BUILDROOT_IMAGES_DIR="${KSB_BUILDROOT_OUTPUT_DIR}/images"
export KSB_BUILDROOT_TARGET_DIR="${KSB_BUILDROOT_OUTPUT_DIR}/target"

# Setup buildroot cache
ksb_buildroot_cache_dir="${KSB_CACHE_DIR}/buildroot"
export BR2_DL_DIR="${ksb_buildroot_cache_dir}/dl"
export BR2_CCACHE_DIR="${ksb_buildroot_cache_dir}/ccache"
export BR2_USE_CCACHE=1

# All cargo deps get vendored into the same directory before building
export KSB_CARGO_VENDOR_DIR="${ksb_buildroot_cache_dir}/cargo-vendor"

cmd="${1:-}"
if [[ "${cmd}" == "" ]]; then
    log_warning "No command given"
    exit 0
fi

ksb-buildroot-configure

if [ "${KSB_BUILDROOT_GIT_CONFIG}" -nt "${KSB_BUILDROOT_CONFIG}" ]; then
    log_warning "Defconfig has been updated by git!"
    log_fatal "Either reset buildroot (erasing any changes), or merge your changes into the new config"
fi

buildroot_command="ksb-buildroot-$cmd"
if ! which "${buildroot_command}" > /dev/null; then
    log_fatal "Unknown command $cmd"
fi

"${buildroot_command}" "${@:2}"

if [ "${KSB_BUILDROOT_CONFIG}" -nt "${KSB_BUILDROOT_GIT_CONFIG}" ]; then
    read -p "Do you want to save buildroot config to git? [y/N]: " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        ksb-buildroot-save
    fi
fi