#!/usr/bin/env bash
#-Help: Pass through to cargo

set -euo pipefail
source "${KSB_SCRIPTS_LIB_DIR}/logging.sh"

ksb_cargo_home="${KSB_WORK_DIR}/cargo"

export RUSTUP_HOME="${ksb_cargo_home}"
export CARGO_HOME="${ksb_cargo_home}"
export CARGO_TARGET_DIR="${KSB_BUILD_DIR}/cargo-target"

# This version should match the toolchain used by the firmware
# as defined in: key-firmware/rust-toolchain.toml
DEFAULT_RUST_TOOLCHAIN="nightly-2024-03-22"

if [[ ! -d "${ksb_cargo_home}" ]]; then
  log_section "Installing cargo"

  mkdir -p "${ksb_cargo_home}"
  ksb-vendor
  "${KSB_VENDOR_DIR}/rustup/rustup-init.sh" -y \
    --no-update-default-toolchain \
    --no-modify-path \
    --component rust-src \
    --profile minimal \
    --default-toolchain ${DEFAULT_RUST_TOOLCHAIN}
fi

mkdir -p "${CARGO_TARGET_DIR}"
source "${ksb_cargo_home}/env"
cargo "${@:1}"