#!/usr/bin/env bash
#-Help: Build/run/flash arduino firmware
#-Use: (keyboard|dials) (build|run|flash)

set -euo pipefail
source "${KSB_SCRIPTS_LIB_DIR}/logging.sh"


# TODO: Detect serial
arduino_serial="/dev/ttyUSB0"

# TODO: Install ravedude with ksb-cargo
# TODO: Support just flashing (use avrdude directly)

firmware="${1}"
firmware_src_dir="${KSB_PROJECT_ROOT}/firmware/${firmware}"
firmware_bin="${KSB_BUILD_DIR}/cargo-target/avr-atmega328p/debug/${firmware}.elf"

if [ ! -d "${firmware_src_dir}" ]; then
  log_fatal "unknown firmware ${firmware}"
fi

source ksb-toolchain avr

pushd "${firmware_src_dir}"
case "${2}" in
  "build")
    ksb-cargo build "${@:3}"
  ;;
  "run")
    export CARGO_TARGET_AVR_ATMEGA328P_RUNNER="ravedude nano-new -cb 115200 -P ${arduino_serial}"
    ksb-cargo run "${@:3}"
  ;;
  "flash")
    ksb-cargo build "${@:3}"

    instruction="flash:w:${firmware_bin}:e"
    avrdude -p atmega328p -c arduino -P "${arduino_serial}" -b 115200 -e -D -U "${instruction}"
  ;;
  *)
    log_fatal "unknown command ${1}"
  ;;
esac
popd

