#!/usr/bin/env bash
#-NoHelp: Internal

set -euo pipefail
source "${KSB_SCRIPTS_LIB_DIR}/logging.sh"

# Has buildroot been setup?
buildroot_configured_stamp="${KSB_BUILDROOT_OUTPUT_DIR}/.stamp"
if [ ! -f "${buildroot_configured_stamp}" ]; then
    ksb-vendor
    ksb-buildroot-build "$(basename "${KSB_BUILDROOT_GIT_CONFIG}")"
fi
touch "${buildroot_configured_stamp}"