#!/usr/bin/env bash
#-Help: Build/run/flash arduino firmware
#-Use: (build|run|flash)

set -euo pipefail
source "${KSB_SCRIPTS_LIB_DIR}/logging.sh"

firmware_src_dir="${KSB_PROJECT_ROOT}/keystation-firmware"

# TODO: Detect serial
arduino_serial="/dev/ttyUSB0"

# TODO: Install ravedude with ksb-cargo
# TODO: Support just flashing (use avrdude directly)

source ksb-toolchain avr

pushd "${firmware_src_dir}"
case "${1}" in
  "build")
    ksb-cargo build "${@:2}"
  ;;
  "run")
    export CARGO_TARGET_AVR_ATMEGA328P_RUNNER="ravedude nano-new -cb 115200 -P ${arduino_serial}"
    ksb-cargo run "${@:2}"
  ;;
  "flash")
    ksb-cargo build "${@:2}"

    firmware_bin="${KSB_BUILD_DIR}/cargo-target/avr-atmega328p/debug/keystation-firmware.elf"
    instruction="flash:w:${firmware_bin}:e"
    avrdude -p atmega328p -c arduino -P "${arduino_serial}" -b 115200 -e -D -U "${instruction}"
  ;;
  "artifact-path")
    echo "${CARGO_TARGET_DIR}/avr-atmega328p/debug/keystation-firmware.elf"
  ;;
  *)
    log_fatal "unknown command ${1}"
  ;;
esac
popd

