#!/usr/bin/env bash
#-Help: Pass through to cargo

set -euo pipefail
source "${KSB_SCRIPTS_LIB_DIR}/logging.sh"

ksb_cargo_home="${KSB_WORK_DIR}/cargo"

export RUSTUP_HOME="${ksb_cargo_home}"
export CARGO_HOME="${ksb_cargo_home}"
export CARGO_TARGET_DIR="${KSB_BUILD_DIR}/cargo-target"

# This version should match the toolchain used by the firmware
# as defined in: key-firmware/rust-toolchain.toml
TOOLCHAIN_AVR="nightly-2024-03-22"

# This version should match the toolchain build by buildroot
# Find by locating toolchain install dir at
# .ksb/build/buildroot/build/host-rust-bin-<version>/version
TOOLCHAIN_SYSTEM="1.74.1"

mkdir -p "${CARGO_TARGET_DIR}"

if [[ ! -d "${ksb_cargo_home}" ]]; then
  log_section "Installing cargo"

  mkdir -p "${ksb_cargo_home}"
  ksb-vendor
  "${KSB_VENDOR_DIR}/rustup/rustup-init.sh" -y \
    --no-update-default-toolchain \
    --no-modify-path


  source "${ksb_cargo_home}/env"

  rustup toolchain install \
    --no-self-update \
    --no-update \
    --component rust-src \
    --profile minimal \
    "${TOOLCHAIN_AVR}"

  rustup toolchain install \
    --no-self-update \
    --no-update \
    "${TOOLCHAIN_SYSTEM}"

else
  source "${ksb_cargo_home}/env"
fi

cargo "${@:1}"