#!/usr/bin/env bash
#-NoHelp: Internal
#-Help: Export the current buildroot configuration to hudos_defconfig
#-Extended: All sensitive keys (wifi settings, etc) will be removed

set -euo pipefail
source "${KSB_SCRIPTS_LIB_DIR}/logging.sh"

pushd "${KSB_BUILDROOT_DIR}"
mkdir -p "${KSB_BUILDROOT_OUTPUT_DIR}"
make savedefconfig BR2_DEFCONFIG="${KSB_BUILDROOT_GIT_CONFIG}" O="${KSB_BUILDROOT_OUTPUT_DIR}"
popd

# These settings should not be saved to git
# sed -i '/^BR2_PACKAGE_HUDOS_NETWORK_WIFI_/d' "${HB_BUILDROOT_GIT_CONFIG}"

touch "${KSB_BUILDROOT_GIT_CONFIG}" "${KSB_BUILDROOT_CONFIG}"