[package]
name = "key-driver"
version = "0.1.0"
edition = "2021"

[dependencies]
midir = { version = "0.10.0", default-features = false, features = ["jack"] }
rppal = "0.19.0"

rs-tty = { path = "../rs-tty" }