KEYBOARD_DAEMON_VERSION = 0.0.1
KEYBOARD_DAEMON_SITE = $(BR2_EXTERNAL_KBS_PATH)/../system-components
KEYBOARD_DAEMON_SITE_METHOD = local
KEYBOARD_DAEMON_SUBDIR = keyboard-daemon
KEYBOARD_DAEMON_INSTALL_TARGET = YES
KEYBOARD_DAEMON_DEPENDENCIES = host-rustc key-firmware jack2

define KEYBOARD_DAEMON_INSTALL_SERVICE
	$(INSTALL) -D -m 755 $(KEYBOARD_DAEMON_PKGDIR)/S50keyboard-daemon $(TARGET_DIR)/etc/init.d/S50keyboard-daemon
endef

KEYBOARD_DAEMON_POST_INSTALL_TARGET_HOOKS += KEYBOARD_DAEMON_INSTALL_SERVICE

KEYBOARD_DAEMON_POST_RSYNC_HOOKS += POST_RSYNC_CARGO_VENDOR

$(eval $(cargo-package))