KEYSTATION_VERSION = 0.0.1
KEYSTATION_SITE = $(BR2_EXTERNAL_KBS_PATH)/package/keystation
KEYSTATION_SITE_METHOD = local
KEYSTATION_INSTALL_TARGET = YES
KEYSTATION_DEPENDENCIES = loadmodules

define KEYSTATION_LINUX_CONFIG_FIXUPS
	$(call KCONFIG_ENABLE_OPT,CONFIG_USB_GADGET)
	$(call KCONFIG_ENABLE_OPT,CONFIG_USB_GADGET_DEBUG)
	$(call KCONFIG_ENABLE_OPT,CONFIG_USB_CONFIGFS)
endef

define KEYSTATION_INSTALL_TARGET_CMDS
	$(INSTALL) -D -m 755 $(KEYSTATION_PKGDIR)/01core $(TARGET_DIR)/etc/modules.d/01core; \
	$(INSTALL) -D -m 644 $(KEYSTATION_PKGDIR)/asound.conf $(TARGET_DIR)/etc/asound.conf;
endef

$(eval $(generic-package))