#!/bin/sh

keystation_bin="keystation"
keystation_path="/usr/bin/${keystation_bin}"
keystation_log="/var/log/${keystation_bin}.log"

[ -x "${keystation_path}" ] || exit 0

umask 077

log() {
	echo "$1" | tee /dev/kmsg >> "${keystation_log}"
}

start() {
    "${keystation_path}"  >> "${keystation_log}" 2>&1 &
}
stop() {
    killall -q "${keystation_bin}"
}
restart() {
    stop
    start
}

case "$1" in
  start)
    log "starting ${keystation_bin}"
    start
    ;;
  stop)
    log "stopping ${keystation_bin}"
    stop
    ;;
  restart|reload)
    log "restarting ${keystation_bin}"
    restart
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $?
