DIALS_FIRMWARE_VERSION = 0.0.1
DIALS_FIRMWARE_SITE = $(BR2_EXTERNAL_KBS_PATH)/../firmware
DIALS_FIRMWARE_SITE_METHOD = local
DIALS_FIRMWARE_SUBDIR = dials
DIALS_FIRMWARE_INSTALL_TARGET = YES

DIALS_FIRMWARE_PROFILE = release
DIALS_FIRMWARE_ARTIFACT_PATH = ${KSB_BUILD_DIR}/cargo-target/avr-atmega328p/$(DIALS_FIRMWARE_PROFILE)/
DIALS_FIRMWARE_BIN = dials.elf

define DIALS_FIRMWARE_BUILD_CMDS
	KSB_NO_LOCK="buildroot" ${KSB} firmware dials build --profile $(DIALS_FIRMWARE_PROFILE);
endef

define DIALS_FIRMWARE_INSTALL_TARGET_CMDS
	mkdir -p $(TARGET_DIR)/usr/share/;
	$(INSTALL) -D -m 655 $(DIALS_FIRMWARE_ARTIFACT_PATH)/$(DIALS_FIRMWARE_BIN) $(TARGET_DIR)/usr/share/$(DIALS_FIRMWARE_BIN)
	$(INSTALL) -D -m 655 $(DIALS_FIRMWARE_ARTIFACT_PATH)/dials-version.txt $(TARGET_DIR)/usr/share/dials-version.txt
endef

$(eval $(generic-package))