#!/bin/sh

cardinal_bin="Cardinal"
cardinal_path="/usr/local/bin/${cardinal_bin}"
cardinal_log="/var/log/${cardinal_bin}.log"

[ -f "${cardinal_path}" ] || exit 0

umask 077

log() {
	echo "$1" | tee /dev/kmsg >> "${cardinal_log}"
}

start() {
# TODO: Try starting with $JACK_START_SERVER defined
    "${cardinal_path}" >> "${cardinal_log}" 2>&1 &

    jack_connect Cardinal:audio_out_1 system:playback_1
    jack_connect Cardinal:audio_out_2 system:playback_2
    jack_connect Cardinal:events-in system:midi_capture_1
    jack_connect Cardinal:midi-out system:midi_playback_1
}
stop() {
    killall -q "${cardinal_bin}"
}
restart() {
    stop
    start
}

case "$1" in
  start)
    log "starting ${cardinal_bin}"
    start
    ;;
  stop)
    log "stopping ${cardinal_bin}"
    stop
    ;;
  restart|reload)
    log "restarting ${cardinal_bin}"
    restart
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $?
