KEY_DRIVER_VERSION = 0.0.1
KEY_DRIVER_SITE = $(BR2_EXTERNAL_KBS_PATH)/../key-driver
KEY_DRIVER_SITE_METHOD = local
KEY_DRIVER_INSTALL_TARGET = YES
KEY_DRIVER_DEPENDENCIES = host-rustc key-firmware jack2

define KEY_DRIVER_INSTALL_SERVICE
	$(INSTALL) -D -m 755 $(KEY_DRIVER_PKGDIR)/S50key-driver $(TARGET_DIR)/etc/init.d/S50key-driver
endef

KEY_DRIVER_POST_INSTALL_TARGET_HOOKS += KEY_DRIVER_INSTALL_SERVICE

define KEY_DRIVER_CARGO_FETCH
# Hacky way to fetch deps
     cd $(KEY_DRIVER_SRCDIR) && \
         PATH=$(HOST_DIR)/bin:$(PATH) $(PKG_CARGO_ENV) cargo fetch
endef

KEY_DRIVER_POST_RSYNC_HOOKS += KEY_DRIVER_CARGO_FETCH

$(eval $(cargo-package))